// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWrtTtAoHfxMJZRbsg6lwFVTbVSFnb0k',
    appId: '1:523884872665:web:0aaf847654f27bf81e8fc8',
    messagingSenderId: '523884872665',
    projectId: 'doordashboard',
    authDomain: 'doordashboard.firebaseapp.com',
    storageBucket: 'doordashboard.appspot.com',
    measurementId: 'G-21HY1HLYZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG--RPmsdNkis-vX3wP-Ehi4YBFSOUXsI',
    appId: '1:523884872665:android:cd28e9daa977345f1e8fc8',
    messagingSenderId: '523884872665',
    projectId: 'doordashboard',
    storageBucket: 'doordashboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahrWOFY3pxPmWZASmFzGUipOZzNOLGAk',
    appId: '1:523884872665:ios:b4a39eed8c58803b1e8fc8',
    messagingSenderId: '523884872665',
    projectId: 'doordashboard',
    storageBucket: 'doordashboard.appspot.com',
    iosBundleId: 'com.example.doordashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahrWOFY3pxPmWZASmFzGUipOZzNOLGAk',
    appId: '1:523884872665:ios:959f29f8ac57740e1e8fc8',
    messagingSenderId: '523884872665',
    projectId: 'doordashboard',
    storageBucket: 'doordashboard.appspot.com',
    iosBundleId: 'com.example.doordashboard.RunnerTests',
  );
}
